message:
   enabled: true
   line1: '&9Welcomer supports unlimited lines and color codes.'
   # Remove the # from the below lines to make the plugin use them.
   # You can also add unlimited lines by copying the format below
   # and replacing the number at the end with the line number.
   #line2: ''
   #line3: ''
   #line4: ''
   #line5: ''
   