message:
    enabled: true
    # Delay in ticks, set to 0 to disable.
    delay: 5
    line1: '&9Welcomer supports unlimited lines and color codes.'
    # Remove the # from the below lines to make the plugin use them.
    # You can also add unlimited lines by copying the format below.
    # and replacing the number at the end with the line number.
    #line2: ''
    #line3: ''
    #line4: '' 
    #line5: ''
console_command:
    enabled: true
    # Delay in ticks, set to 0 to disable.
    delay: 5
    # PLAYER will be replaced with the player's name
    # This is an example of sending a title to a player
    cmd1: 'title PLAYER title [{"text":"Title by Welcomer","color":"blue"}]'
    # Remove the # from the below cmds to make the plugin use them.
    # You can also add unlimited lines by copying the format below.
    # and replacing the number at the end with the line number.
    #cmd2: ''
    #cmd3: ''
    #cmd4: ''
    #cmd5:  